#!/bin/bash

CACHE_TAG=${CACHE_TAG#${DOCKER_REPO##*/}-}

if [[ $CACHE_TAG =~ '-' ]]
then
  TAG=${CACHE_TAG%-*}
  SEP='-'
  VER=${CACHE_TAG##*-}
else
  TAG=''
  SEP=''
  VER=${CACHE_TAG}
fi

if [ "$VER" == latest ]
then
  VER=`docker run --rm ${IMAGE_NAME} git describe --tags`
fi

NEW_NAME=${DOCKER_REPO}:${TAG}${SEP}${VER}

if [ "${DOCKER_REPO}:${CACHE_TAG}" != "${NEW_NAME}" ]
then
  docker tag ${IMAGE_NAME} ${NEW_NAME}
  docker push ${NEW_NAME}
fi
