#!/bin/bash

ARRAY=(${IMAGE_NAME/:/ })
PREFIX=${ARRAY[0]}
SUFFIX=${ARRAY[1]}

if [[ $SUFFIX =~ '-' ]]
then
  TAG=${SUFFIX%-*}
  SEP='-'
  VER=${SUFFIX##*-}
else
  TAG=''
  SEP=''
  VER=${SUFFIX}
fi

if [ "$VER" == latest ]
then
  VER=`docker run --rm ${IMAGE_NAME} git describe --tags`
else
  VER=latest
fi

NEW_NAME=${PREFIX}:${TAG}${SEP}${VER}

if [ "${IMAGE_NAME}" != "${NEW_NAME}" ]
then
  docker tag ${IMAGE_NAME} ${NEW_NAME}
  docker push ${NEW_NAME}
fi
