#!/bin/bash

ARRAY=(${IMAGE_NAME/:/ })
PREFIX=${ARRAY[0]}
SUFFIX=${ARRAY[1]}

SUFFIX=`echo ${SUFFIX} | grep -o '.*-'`

NEW_NAME=${PREFIX}:${SUFFIX}latest

if [ "${IMAGE_NAME}" != "${NEW_NAME}" ]
then
  docker tag ${IMAGE_NAME} ${NEW_NAME}
  docker push ${NEW_NAME}
fi
