#!/bin/bash -x

#remove repo name from beginning of tag
DOCKER_TAG=${DOCKER_TAG#${DOCKER_REPO##*/}-}

if [[ $DOCKER_TAG =~ '-' ]]
then
  TAG=${DOCKER_TAG%-*}
  SEP='-'
  VER=${DOCKER_TAG##*-}
else
  TAG=''
  SEP=''
  VER=${DOCKER_TAG}
fi

VER=latest

NEW_NAME=${DOCKER_REPO}:${TAG}${SEP}${VER}

if [ "${DOCKER_REPO}:${DOCKER_TAG}" != "${NEW_NAME}" ]
then
  docker tag ${IMAGE_NAME} ${NEW_NAME}
  docker push ${NEW_NAME}
fi
